version: '3.7'
services:
  apache:
    network_mode: host
    image: bitnami/apache:2.4.41
    ports:
      - 8080:8080
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 100000
    volumes:
      - ./apache/my_vhost.conf:/opt/bitnami/apache/conf/vhosts/my_vhost.conf
      - ./apache/httpd-worker.conf:/opt/bitnami/apache/conf/httpd.conf
      - ./apache/extra/httpd-mpm.conf:/opt/bitnami/apache/conf/extra/httpd-mpm.conf
