version: '3.7'
services:
  haproxy:
    network_mode: host
    image: haproxy:2.1.2
    ports:
      - 8080:8080
    ulimits:
      nproc: 65535
      nofile:
        soft: 25000
        hard: 40000
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
