version: '3.7'
services:
  nginx:
    image: bitnami/nginx:1.16.1
    ports:
      - 8080:8080
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - ./hosts:/etc/hosts:ro
