version: '3'
services:
  nginx:
    image: bitnami/nginx:1.16.1
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - /etc/hosts:/etc/hosts:ro
