version: '3'
services:
  nginx:
    image: bitnami/nginx:1.16.1
    links:
      - node-backend0
      - node-backend1
      - node-backend2
      - node-backend3
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
  node-backend0: # we don't use docker-compose scale here, because we want to test apache/nginx load balancing
    build:
      context: ./node-backend
  node-backend1:
    build:
      context: ./node-backend
  node-backend2:
    build:
      context: ./node-backend
  node-backend3:
    build:
      context: ./node-backend
